[package]
name = "rust-8080"
version = "0.1.0"
authors = ["Alexandre Janin <alexandrejanin92@gmail.com>"]
edition = "2018"

[features]
default = []
logging = []

[dependencies]
minifb = "0.11.2"
i8080 = { path = "../i8080-master" }
